### ISSUE TITLE
BR Authority data source error (Automated error report)

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#105]
Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 164, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 222, in run
    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)
  File "/home/vmagent/app/pipelines/epidemiology/br_authority.py", line 163, in parse
    return super().parse(sources, aux, **parse_opts)
  File "/home/vmagent/app/lib/data_source.py", line 97, in parse
    return self.parse_dataframes(self._read(sources, **read_opts), aux, **parse_opts)
  File "/home/vmagent/app/lib/data_source.py", line 78, in _read
    return {name: read_file(file_path, **read_opts) for name, file_path in file_paths.items()}
  File "/home/vmagent/app/lib/data_source.py", line 78, in <dictcomp>
    return {name: read_file(file_path, **read_opts) for name, file_path in file_paths.items()}
  File "/home/vmagent/app/lib/io.py", line 95, in read_file
    return pandas.read_csv(path, **{**default_read_opts, **read_opts})
  File "/env/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/env/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/env/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1937, in __init__
    _validate_usecols_names(usecols, self.orig_names)
  File "/env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1233, in _validate_usecols_names
    "Usecols do not match columns, "
ValueError: Usecols do not match columns, columns expected but not found: ['sexo', 'dataEncerramento', 'classificacaoFinal', 'evolucaoCaso', 'estadoIBGE', 'dataInicioSintomas', 'idade', 'resultadoTeste', 'dataTeste', 'municipioIBGE']

**Comment by owahltinez** [comment]
This was only a transient issue
