### ISSUE TITLE
GB Authority L3 Source error (Automated error report)

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#106]
Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 164, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 222, in run
    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)
  File "/home/vmagent/app/pipelines/epidemiology/gb_authority.py", line 191, in parse
    data.areaCode = data.areaCode.apply(_apply_area_code_map)
  File "/env/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'areaCode'

**Comment by themonk911** [comment]
Looks like this was a one off - closing.
