### ISSUE TITLE
PH Authority error (Automated error report)

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#107]
Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 164, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 222, in run
    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)
  File "/home/vmagent/app/lib/data_source.py", line 97, in parse
    return self.parse_dataframes(self._read(sources, **read_opts), aux, **parse_opts)
  File "/home/vmagent/app/pipelines/epidemiology/ph_authority.py", line 48, in parse_dataframes
    nan_recovered_mask = cases.date_new_recovered.isna() & (cases["_prognosis"] == "Recovered")
  File "/env/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'date_new_recovered'

**Comment by owahltinez** [comment]
Transient failure, it is now working again
