### ISSUE TITLE
Luxemberg data source fails to fetch

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#127]
```
Traceback (most recent call last):
  File "/home/runner/work/covid-19-open-data/covid-19-open-data/src/test/test_source_run.py", line 108, in test_dry_run_pipeline
    list(process_map(_test_data_pipeline, list(get_pipeline_names()), max_workers=2))
  File "/home/runner/work/covid-19-open-data/covid-19-open-data/src/lib/concurrent.py", line 41, in process_map
    return concurrent._executor_map(_ProcessExecutor, map_func, map_iter, **tqdm_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 39, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables), **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/tqdm/std.py", line 1087, in __iter__
    for obj in iterable:
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
RuntimeError: Data source run failed: epidemiology LuxembourgDataSource {'name': 'pipelines.epidemiology.lu_authority.LuxembourgDataSource', 'fetch': [{'url': 'https://data.public.lu/fr/datasets/r/c9fd593c-fe7a-43ec-9ae4-09a6c1604b6b', 'opts': {'ext': 'xls'}}], 'parse': {'sep': ';', 'encoding': 'ISO-8859-1'}, 'test': {'metadata_query': "key == 'LU'"}, 'automation': {'job_group': '50'}}
```

**Comment by themonk911** [comment]
This is currently breaking the unit tests.

**Comment by themonk911** [comment]
Note the same source is also used for hospitalizations.

**Comment by owahltinez** [comment]
It must have been a transient failure, it is working now. This has historically been a flaky data source.
