### ISSUE TITLE
Slovenia data source fails to run due to key error on "date" field

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#13]
```
/home/vmagent/app/lib/error_logger.py:30: UserWarning: [2020-07-30T13:02:38.6778][SloveniaDataSource] Error running data source SloveniaDataSource with config {'name': 'pipelines.epidemiology.si_authority.SloveniaDataSource', 'fetch': [{'url': 'https://www.gov.si/assets/vlada/Koronavirus-podatki/en/EN_Covid-19-all-data.xlsx'}], 'test': {'metadata_query': "key == 'SI'"}, 'automation': {'job_group': '24'}}

Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'
```

**Comment by owahltinez** [comment]
They changed the language of the column names. Again. Fixed via #16.
