### ISSUE TITLE
NoaaGsodDataSource fails to run

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#151]
```{
  "insertId": "xyxm71tk2d0yauboi",
  "jsonPayload": {
    "config": {
      "fetch": [
        {
          "name": "inventory",
          "url": "https://www1.ncdc.noaa.gov/pub/data/noaa/isd-history.csv"
        },
        {
          "url": "https://www.ncei.noaa.gov/data/global-summary-of-the-day/archive/2020.tar.gz",
          "name": "gsod"
        },
        {
          "url": "https://storage.googleapis.com/covid19-open-data/v2/geography.csv",
          "name": "geography"
        }
      ],
      "automation": {
        "job_group": "0"
      },
      "test": {
        "skip": true
      },
      "name": "pipelines.weather.noaa_gsod.NoaaGsodDataSource",
      "schedule": "0 */4 * * *"
    },
    "timestamp": "2020-09-07T09:35:30.0935",
    "source_name": "NoaaGsodDataSource",
    "message": "Error running data source.",
    "traceback": "Traceback (most recent call last):\n  File \"/home/vmagent/app/lib/pipeline.py\", line 163, in _run_wrapper\n    return data_source.run(output_folder, cache, aux)\n  File \"/home/vmagent/app/lib/data_source.py\", line 227, in run\n    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)\n  File \"/home/vmagent/app/pipelines/weather/noaa_gsod.py\", line 200, in parse\n    return concat(records)\n  File \"/env/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 281, in concat\n    sort=sort,\n  File \"/env/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 329, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
    "classname": "NoaaGsodDataSource"
  },
  "timestamp": "2020-09-07T09:35:30Z",
}
```

**Comment by themonk911** [comment]
Traceback (Formatted)

```
Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 163, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 227, in run
    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)
  File "/home/vmagent/app/pipelines/weather/noaa_gsod.py", line 200, in parse
    return concat(records)
  File "/env/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 281, in concat
    sort=sort,
  File "/env/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 329, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by owahltinez** [comment]
This seems like a transient issue to me, I'll keep an eye on it and if I see a successful run then I'll close this

**Comment by themonk911** [comment]
I don't see this recurring, will reopen if it does.
