### ISSUE TITLE
Florida data source fails to run

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#161]
```
"Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 163, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 223, in run
    data = self.fetch(output_folder, cache, fetch_opts)
  File "/home/vmagent/app/pipelines/epidemiology/us_fl_authority.py", line 132, in fetch
    self._get_county_cases().to_csv(file_path, index=False)
  File "/home/vmagent/app/pipelines/epidemiology/us_fl_authority.py", line 93, in _get_county_cases
    cases = DataFrame.from_records(_r_get_county_cases())
  File "/home/vmagent/app/pipelines/epidemiology/us_fl_authority.py", line 91, in _r_get_county_cases
    return rows + _r_get_county_cases(offset + len(rows))
  File "/home/vmagent/app/pipelines/epidemiology/us_fl_authority.py", line 91, in _r_get_county_cases
    return rows + _r_get_county_cases(offset + len(rows))
  File "/home/vmagent/app/pipelines/epidemiology/us_fl_authority.py", line 91, in _r_get_county_cases
    return rows + _r_get_county_cases(offset + len(rows))
  [Previous line repeated 23 more times]
  File "/home/vmagent/app/pipelines/epidemiology/us_fl_authority.py", line 86, in _r_get_county_cases
    raise exc
  File "/home/vmagent/app/pipelines/epidemiology/us_fl_authority.py", line 83, in _r_get_county_cases
    res = requests.get(_url_tpl.format(offset=offset)).json()["features"]
KeyError: 'features'
"
```

**Comment by themonk911** [comment]
Looks to be a change in API, also see the following message in the logs.

`message: "{"error":{"code":400,"message":"Cannot perform query. Invalid query parameters.","details":["Unable to perform query. Please check your parameters."]}}"`

**Comment by owahltinez** [comment]
It must have been a transient failure, I just tested it and it works as-is
