### ISSUE TITLE
Delaware data source fails to run

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#163]
```
Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 163, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 223, in run
    data = self.fetch(output_folder, cache, fetch_opts)
  File "/home/vmagent/app/lib/data_source.py", line 74, in fetch
    for idx, source_config in enumerate(fetch_opts)
  File "/home/vmagent/app/lib/data_source.py", line 74, in <dictcomp>
    for idx, source_config in enumerate(fetch_opts)
  File "/home/vmagent/app/lib/net.py", line 58, in download_snapshot
    download(url, file_handle, **download_opts)
  File "/home/vmagent/app/lib/net.py", line 81, in download
    req.raise_for_status()
  File "/env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://myhealthycommunity.dhss.delaware.gov/locations/state/download_covid_19_data
```

**Comment by themonk911** [comment]
Going to that link manually leads to an "Acceptable use" agreement page. May need some fancier automation to autoclick?

**Comment by owahltinez** [comment]
Currently the data source does not even load for me. They have had many server issues in the past, it seems those are not fully resolved yet...

**Comment by themonk911** [comment]
I'm keeping an eye on this, it's a sporadic failure (3 times in the last week). Closing this issue, since there is nothing we can do to fix it.
