### ISSUE TITLE
Luxemburg data source fails to run

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#164]
```
Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 163, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 227, in run
    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)
  File "/home/vmagent/app/lib/data_source.py", line 99, in parse
    return self.parse_dataframes(self._read(sources, **read_opts), aux, **parse_opts)
  File "/home/vmagent/app/lib/data_source.py", line 79, in _read
    return {name: read_file(file_path, **read_opts) for name, file_path in file_paths.items()}
  File "/home/vmagent/app/lib/data_source.py", line 79, in <dictcomp>
    return {name: read_file(file_path, **read_opts) for name, file_path in file_paths.items()}
  File "/home/vmagent/app/lib/io.py", line 99, in read_file
    return pandas.read_excel(path, **{**default_read_opts, **read_opts})
  File "/env/lib/python3.7/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
TypeError: read_excel() got an unexpected keyword argument 'sep'
```

**Comment by themonk911** [comment]
Looks like a bad configuration?

**Comment by owahltinez** [comment]
Nice catch! Yes, the config appears to be wrong

**Comment by themonk911** [comment]
This is still happening - looks like it's the same config problem but in hospitalizations.
