### ISSUE TITLE
Mexico data source fails to fetch

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#17]
```
/home/vmagent/app/lib/error_logger.py:30: UserWarning: [2020-07-30T13:16:24.1400][MexicoDataSource] Error running data source MexicoDataSource with config {'name': 'pipelines.epidemiology.mx_authority.MexicoDataSource', 'fetch': [{'url': 'http://187.191.75.115/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip'}], 'parse': {'encoding': 'ISO-8859-1'}, 'test': {'skip': True, 'metadata_query': "key.str.match('MX_.+')"}, 'automation': {'job_group': '29'}}
warnings.warn(f"{''.join((f'[{tag}]' for tag in tags))} {msg}")
Traceback (most recent call last): File "/env/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn (self._dns_host, self.port), self.timeout, **extra_kw File "/env/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection raise err File "/env/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection sock.connect(sa) TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last): File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen chunked=chunked, File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request conn.request(method, url, **httplib_request_kw) File "/opt/python3.7/lib/python3.7/http/client.py", line 1229, in request self._send_request(method, url, body, headers, encode_chunked) File "/opt/python3.7/lib/python3.7/http/client.py", line 1275, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/opt/python3.7/lib/python3.7/http/client.py", line 1224, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/opt/python3.7/lib/python3.7/http/client.py", line 1016, in _send_output self.send(msg) File "/opt/python3.7/lib/python3.7/http/client.py", line 956, in send self.connect() File "/env/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect conn = self._new_conn() File "/env/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn self, "Failed to establish a new connection: %s" % e urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f75bebc5a58>: Failed to establish a new connection: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last): File "/env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send timeout=timeout File "/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2] File "/env/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='187.191.75.115', port=80): Max retries exceeded with url: /gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75bebc5a58>: Failed to establish a new connection: [Errno 110] Connection timed out'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last): File "/home/vmagent/app/lib/pipeline.py", line 169, in _run_wrapper return data_source.run(output_folder, cache, aux) File "/home/vmagent/app/lib/data_source.py", line 201, in run data = self.fetch(output_folder, cache, fetch_opts) File "/home/vmagent/app/lib/data_source.py", line 71, in fetch for idx, source_config in enumerate(fetch_opts) File "/home/vmagent/app/lib/data_source.py", line 71, in <dictcomp> for idx, source_config in enumerate(fetch_opts) File "/home/vmagent/app/lib/net.py", line 58, in download_snapshot download(url, file_handle, **download_opts) File "/home/vmagent/app/lib/net.py", line 79, in download req = requests.get(url, headers=headers) File "/env/lib/python3.7/site-packages/requests/api.py", line 76, in get return request('get', url, params=params, **kwargs) File "/env/lib/python3.7/site-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "/env/lib/python3.7/site-packages/requests/sessions.py", line 530, in request resp = self.send(prep, **send_kwargs) File "/env/lib/python3.7/site-packages/requests/sessions.py", line 643, in send r = adapter.send(request, **kwargs) File "/env/lib/python3.7/site-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPConnectionPool(host='187.191.75.115', port=80): Max retries exceeded with url: /gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75bebc5a58>: Failed to establish a new connection: [Errno 110] Connection timed out'))
/home/vmagent/app/lib/error_logger.py:30: UserWarning: [2020-07-30T13:16:24.1410][DataPipeline] No output for MexicoDataSource with config {'name': 'pipelines.epidemiology.mx_authority.MexicoDataSource', 'fetch': [{'url': 'http://187.191.75.115/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip'}], 'parse': {'encoding': 'ISO-8859-1'}, 'test': {'skip': True, 'metadata_query': "key.str.match('MX_.+')"}, 'automation': {'job_group': '29'}}
warnings.warn(f"{''.join((f'[{tag}]' for tag in tags))} {msg}")
```

**Comment by owahltinez** [comment]
This is a very flakey data source. It tends to work better during the morning times in the Americas... Perhaps we should look into caching it somewhere

**Comment by owahltinez** [comment]
Mexico started publishing the file in a much more stable server, which we switched to via #29.
