### ISSUE TITLE
All Czech data sources failed to run

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#180]
This includes the following,

- CzechRepublicAgeSexDataSource
- CzechRepublicL1TestedDataSource
- CzechRepublicL3DataSource

with the same root cause, server unavailable.

```
"Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 163, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 223, in run
    data = self.fetch(output_folder, cache, fetch_opts)
  File "/home/vmagent/app/lib/data_source.py", line 74, in fetch
    for idx, source_config in enumerate(fetch_opts)
  File "/home/vmagent/app/lib/data_source.py", line 74, in <dictcomp>
    for idx, source_config in enumerate(fetch_opts)
  File "/home/vmagent/app/lib/net.py", line 58, in download_snapshot
    download(url, file_handle, **download_opts)
  File "/home/vmagent/app/lib/net.py", line 81, in download
    req.raise_for_status()
  File "/env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/osoby.csv
```

**Comment by k00ni** [comment]
I tried the URL at the end (`https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/osoby.csv`) and it worked. Can you check again?

**Comment by themonk911** [comment]
Yes, I've confirmed this is now fetching correctly again - looks like an intermittent error with the source, will close this issue.
