### ISSUE TITLE
Texas Data source failing with missing sheet error

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#184]
```
{
  "insertId": "5ycivhwscd2yq5806",
  "jsonPayload": {
    "source_name": "TexasDataSource",
    "message": "Error running data source.",
    "classname": "TexasDataSource",
    "traceback": "Traceback (most recent call last):\n  File \"/env/lib/python3.7/site-packages/xlrd/book.py\", line 474, in sheet_by_name\n    sheetx = self._sheet_names.index(sheet_name)\nValueError: 'Tests by day' is not in list\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/vmagent/app/lib/pipeline.py\", line 163, in _run_wrapper\n    return data_source.run(output_folder, cache, aux)\n  File \"/home/vmagent/app/lib/data_source.py\", line 232, in run\n    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)\n  File \"/home/vmagent/app/pipelines/epidemiology/us_tx_authority.py\", line 82, in parse\n    df = sheet_processor(read_file(sources[0], sheet_name=sheet_name))\n  File \"/home/vmagent/app/lib/io.py\", line 99, in read_file\n    return pandas.read_excel(path, **{**default_read_opts, **read_opts})\n  File \"/env/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 296, in wrapper\n    return func(*args, **kwargs)\n  File \"/env/lib/python3.7/site-packages/pandas/io/excel/_base.py\", line 334, in read_excel\n    mangle_dupe_cols=mangle_dupe_cols,\n  File \"/env/lib/python3.7/site-packages/pandas/io/excel/_base.py\", line 926, in parse\n    **kwds,\n  File \"/env/lib/python3.7/site-packages/pandas/io/excel/_base.py\", line 439, in parse\n    sheet = self.get_sheet_by_name(asheetname)\n  File \"/env/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py\", line 44, in get_sheet_by_name\n    return self.book.sheet_by_name(name)\n  File \"/env/lib/python3.7/site-packages/xlrd/book.py\", line 476, in sheet_by_name\n    raise XLRDError('No sheet named <%r>' % sheet_name)\nxlrd.biffh.XLRDError: No sheet named <'Tests by day'>\n",
    "timestamp": "2020-09-18T15:02:36.4081",
    "config": {
      "test": {
        "skip": true,
        "metadata_query": "key == 'US_TX'"
      },
      "fetch": [
        {
          "url": "https://dshs.texas.gov/coronavirus/TexasCOVID19CaseCountData.xlsx"
        }
      ],
      "name": "pipelines.epidemiology.us_tx_authority.TexasDataSource",
      "automation": {
        "job_group": "32"
      }
    }
  },

  "timestamp": "2020-09-18T15:02:36Z",

}
```

**Comment by themonk911** [comment]
```
"Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/xlrd/book.py", line 474, in sheet_by_name
    sheetx = self._sheet_names.index(sheet_name)
ValueError: 'Tests by day' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 163, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 232, in run
    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)
  File "/home/vmagent/app/pipelines/epidemiology/us_tx_authority.py", line 82, in parse
    df = sheet_processor(read_file(sources[0], sheet_name=sheet_name))
  File "/home/vmagent/app/lib/io.py", line 99, in read_file
    return pandas.read_excel(path, **{**default_read_opts, **read_opts})
  File "/env/lib/python3.7/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 334, in read_excel
    mangle_dupe_cols=mangle_dupe_cols,
  File "/env/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 926, in parse
    **kwds,
  File "/env/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 439, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/env/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 44, in get_sheet_by_name
    return self.book.sheet_by_name(name)
  File "/env/lib/python3.7/site-packages/xlrd/book.py", line 476, in sheet_by_name
    raise XLRDError('No sheet named <%r>' % sheet_name)
xlrd.biffh.XLRDError: No sheet named <'Tests by day'>
```

**Comment by owahltinez** [comment]
Fixed via https://github.com/GoogleCloudPlatform/covid-19-open-data/pull/237
