### ISSUE TITLE
US_TX data source fails parsing

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#20]
```
Traceback (most recent call last): File "/home/vmagent/app/pipelines/epidemiology/us_tx_authority.py", line 44, in _parse_trends return _rename_columns(data, column_adapter) File "/home/vmagent/app/pipelines/epidemiology/us_tx_authority.py", line 29, in _rename_columns return data[column_adapter.values()] File "/env/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__ indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1] File "/env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing File "/env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer raise KeyError(f"None of [{key}] are in the [{axis_name}]") KeyError: "None of [Index(['date', 'total_confirmed', 'total_deceased', 'new_confirmed',\n 'new_deceased'],\n dtype='object')] are in the [columns]"
During handling of the above exception, another exception occurred:
Traceback (most recent call last): File "/home/vmagent/app/lib/pipeline.py", line 169, in _run_wrapper return data_source.run(output_folder, cache, aux) File "/home/vmagent/app/lib/data_source.py", line 205, in run data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts) File "/home/vmagent/app/pipelines/epidemiology/us_tx_authority.py", line 73, in parse df = sheet_processor(read_file(sources[0], sheet_name=sheet_name)) File "/home/vmagent/app/pipelines/epidemiology/us_tx_authority.py", line 46, in _parse_trends return _rename_columns(data.iloc[1:], column_adapter) File "/home/vmagent/app/pipelines/epidemiology/us_tx_authority.py", line 29, in _rename_columns return data[column_adapter.values()] File "/env/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__ indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1] File "/env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing File "/env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1646, in _validate_read_indexer raise KeyError(f"{not_found} not in index") KeyError: "['new_deceased'] not in index"
/home/vmagent/app/lib/error_logger.py:30: UserWarning: [2020-07-30T13:12:33.1050][DataPipeline] No output for TexasDataSource with config {'name': 'pipelines.epidemiology.us_tx_authority.TexasDataSource', 'fetch': [{'url': 'https://dshs.texas.gov/coronavirus/TexasCOVID19CaseCountData.xlsx'}], 'test': {'metadata_query': "key == 'US_TX'", 'skip': True}, 'automation': {'job_group': '74'}}
warnings.warn(f"{''.join((f'[{tag}]' for tag in tags))} {msg}")
```

**Comment by themonk911** [comment]
The stack trace has evolved to 
```
Traceback (most recent call last):
  File "/home/vmagent/app/pipelines/epidemiology/us_tx_authority.py", line 44, in _parse_trends
    return _rename_columns(data, column_adapter)
  File "/home/vmagent/app/pipelines/epidemiology/us_tx_authority.py", line 29, in _rename_columns
    return data[column_adapter.values()]
  File "/env/lib/python3.7/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['date', 'total_confirmed', 'total_deceased', 'new_confirmed',\n       'new_deceased'],\n      dtype='object')] are in the [columns]"
```
