### ISSUE TITLE
Errors parsing PT data sources

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#23]
```
/open-covid-19/data/src/lib/error_logger.py:30: UserWarning: [2020-07-30T15:33:15.7513][PtCovid19L1DataSource] Error running data source PtCovid19L1DataSource with config {'name': 'pipelines.epidemiology.pt_covid19.PtCovid19L1DataSource', 'fetch': [{'url': 'https://raw.githubusercontent.com/carlospramalheira/covid19/master/datasets/PT_COVID_TimeSeries.csv'}], 'test': {'metadata_query': "key.str.match('PT')"}, 'automation': {'job_group': '56'}}
  warnings.warn(f"{''.join((f'[{tag}]' for tag in tags))} {msg}")
Traceback (most recent call last):
  File "Documents/open-covid-19/data/src/lib/pipeline.py", line 169, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "Documents/open-covid-19/data/src/lib/data_source.py", line 205, in run
    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)
  File "Documents/open-covid-19/data/src/lib/data_source.py", line 86, in parse
    return self.parse_dataframes(self._read(sources, **read_opts), aux, **parse_opts)
  File "Documents/open-covid-19/data/src/lib/data_source.py", line 76, in _read
    return {name: read_file(file_path, **read_opts) for name, file_path in file_paths.items()}
  File "Documents/open-covid-19/data/src/lib/data_source.py", line 76, in <dictcomp>
    return {name: read_file(file_path, **read_opts) for name, file_path in file_paths.items()}
  File "Documents/open-covid-19/data/src/lib/io.py", line 93, in read_file
    path, **{**{"keep_default_na": False, "na_values": ["", "N/A"]}, **read_opts}
  File "Documents/open-covid-19/open-covid-env/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "Documents/open-covid-19/open-covid-env/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "Documents/open-covid-19/open-covid-env/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "Documents/open-covid-19/open-covid-env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "Documents/open-covid-19/open-covid-env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by owahltinez** [comment]
Transient issue, working now
