### ISSUE TITLE
Mexico data source fails to process

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#255]
```
{
  "insertId": "rxdfd8e3b35eygmb9",
  "jsonPayload": {
    "logname": "MexicoDataSource",
    "classname": "MexicoDataSource",
    "message": "Error running data source.",
    "source_name": "MexicoDataSource",
    "traceback": "Traceback (most recent call last):\n  File \"/env/lib/python3.7/site-packages/pandas/core/indexes/base.py\", line 2891, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 101, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item\nKeyError: '_diagnosis'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/vmagent/app/lib/pipeline.py\", line 162, in _run_wrapper\n    return data_source.run(output_folder, cache, aux)\n  File \"/home/vmagent/app/lib/data_source.py\", line 227, in run\n    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)\n  File \"/home/vmagent/app/lib/data_source.py\", line 91, in parse\n    return self.parse_dataframes(self._read(sources, **read_opts), aux, **parse_opts)\n  File \"/home/vmagent/app/pipelines/epidemiology/mx_authority.py\", line 117, in parse_dataframes\n    cases = cases[cases[\"_diagnosis\"] == 1]\n  File \"/env/lib/python3.7/site-packages/pandas/core/frame.py\", line 2902, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/env/lib/python3.7/site-packages/pandas/core/indexes/base.py\", line 2893, in get_loc\n    raise KeyError(key) from err\nKeyError: '_diagnosis'\n",
    "config": {
      "name": "pipelines.epidemiology.mx_authority.MexicoDataSource",
      "parse": {
        "encoding": "ISO-8859-1"
      },
      "fetch": [
        {
          "url": "http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip"
        }
      ],
      "test": {
        "skip": true,
        "metadata_query": "key.str.match(\"MX_.+\")"
      },
      "automation": {
        "job_group": "31"
      }
    },
    "timestamp": "2020-10-22T09:27:11.1312"
  },
  "timestamp": "2020-10-22T09:27:11Z",
  "logName": "projects/github-open-covid-19/logs/appengine.googleapis.com%2Fstderr",
  "receiveTimestamp": "2020-10-22T09:27:13.963574047Z"
}
```

**Comment by themonk911** [comment]
```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '_diagnosis'
```
