### ISSUE TITLE
publish.py shows memory issues when trying to convert main.csv to json

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#40]
```
Traceback (most recent call last):
  File "/srv/publish.py", line 237, in try_json_covert
    convert_csv_to_json_records(schema, csv_file, json_output)
  File "/srv/lib/memory_efficient.py", line 215, in convert_csv_to_json_records
    raise ValueError(f"Size of {csv_file} too large for conversion: {file_size // 1E6} MB")
ValueError: Size of /tmp/tmp6beg7d3c/public/main.csv too large for conversion: 403.0 MB
```

**Comment by themonk911** [comment]
Similar for weather.csv 
```
Traceback (most recent call last):
  File "/home/vmagent/app/publish.py", line 237, in try_json_covert
    convert_csv_to_json_records(schema, csv_file, json_output)
  File "/home/vmagent/app/lib/memory_efficient.py", line 215, in convert_csv_to_json_records
    raise ValueError(f"Size of {csv_file} too large for conversion: {file_size // 1E6} MB")
ValueError: Size of /tmp/tmpxhfcf5ki/public/weather.csv too large for conversion: 243.0 MB
```

**Comment by owahltinez** [comment]
This is WAI since it would take way too long to convert CSV to JSON, and the resulting JSON file is >1GB. We need to update the documentation.

**Comment by themonk911** [comment]
Looks like we're no longer referencing these two json files in the doc. Closing this issue.
