### ISSUE TITLE
Worldbank datasource fails to fetch

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#66]
```
Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 164, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 226, in run
    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)
  File "/home/vmagent/app/pipelines/worldbank/worldbank.py", line 62, in parse
    download(sources[0], buffer, progress=True)
  File "/home/vmagent/app/lib/net.py", line 85, in download
    req.raise_for_status()
  File "/env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://databank.worldbank.org/data/download/WDI_csv.zip
```

**Comment by owahltinez** [comment]
It looks like WorldBank is having issues keeping their servers up...
