### ISSUE TITLE
Error downloading Google sheet

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#72]
```
Traceback (most recent call last):
  File "/home/vmagent/app/appengine.py", line 169, in _pull_source
    download(url, buffer)
  File "/home/vmagent/app/lib/net.py", line 80, in download
    req.raise_for_status()
  File "/env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.google.com/ServiceLogin?service=wise&passive=1209600&continue=https://doc-00-78-sheets.googleusercontent.com/pub/l5l039s6ni5uumqbsj9o11lmdc/7dcte5qc1e7d2nuuf42gnqinl4/1597148435000/114544363600438953716/*/e@2PACX-1vQKB9-H7tQmfs_MwoITnT8Z0j6qxPXkEQAL4DpgZ2gLRjGzR_pr4Oew-9XjYOClHbqqWT69Rrg_Tp4h?output%3Dcsv&followup=https://doc-00-78-sheets.googleusercontent.com/pub/l5l039s6ni5uumqbsj9o11lmdc/7dcte5qc1e7d2nuuf42gnqinl4/1597148435000/114544363600438953716/*/e@2PACX-1vQKB9-H7tQmfs_MwoITnT8Z0j6qxPXkEQAL4DpgZ2gLRjGzR_pr4Oew-9XjYOClHbqqWT69Rrg_Tp4h?output%3Dcsv&ltmpl=sheets
```

**Comment by owahltinez** [comment]
I can't find the URL referenced in this bug anywhere in the config files, please reopen if it's still visible in the logs
