### ISSUE TITLE
CZ hospitalization source fails with parsing error

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#75]
Looks like a change in the sheet naming,

```
Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 164, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 226, in run
    data = self.parse(data, {name: df.copy() for name, df in aux.items()}, **parse_opts)
  File "/home/vmagent/app/pipelines/hospitalizations/cz_authority.py", line 30, in parse
    data = page.select("#panel3-hospitalization")[0]
IndexError: list index out of range
```

**Comment by owahltinez** [comment]
Transient issue, it is now working
