### ISSUE TITLE
Brazil data source fails to fetch

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#97]
Traceback (most recent call last):
  File "/home/vmagent/app/lib/pipeline.py", line 164, in _run_wrapper
    return data_source.run(output_folder, cache, aux)
  File "/home/vmagent/app/lib/data_source.py", line 222, in run
    data = self.fetch(output_folder, cache, fetch_opts)
  File "/home/vmagent/app/pipelines/epidemiology/br_authority.py", line 158, in fetch
    return super().fetch(output_folder, cache, fetch_opts)
  File "/home/vmagent/app/lib/data_source.py", line 73, in fetch
    for idx, source_config in enumerate(fetch_opts)
  File "/home/vmagent/app/lib/data_source.py", line 73, in <dictcomp>
    for idx, source_config in enumerate(fetch_opts)
  File "/home/vmagent/app/lib/net.py", line 58, in download_snapshot
    download(url, file_handle, **download_opts)
  File "/home/vmagent/app/lib/net.py", line 80, in download
    req.raise_for_status()
  File "/env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/dados-sp.csv

**Comment by owahltinez** [comment]
It is now working again
